name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: rafaelwebber
          outputs: |
            dist/github-contribution-grid-snake.svg
