name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite
  workflow_dispatch:      # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Snake Game (SVG only)
        uses:  Platane/snk@refs/heads/svg-only
        with:
          github_user_name: rafaelwebber
          outputs: dist/github-contribution-grid-snake.svg
          debug: true

      - name: Commit generated files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake SVG" || echo "No changes to commit"

      - name: Push to output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'Generate Snake Game'
          add: 'dist/github-contribution-grid-snake.svg'
          push: origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
