name: Sync Fork with Original

on:
  schedule:
    - cron: '0 3 * * *' # todo dia às 03:00 da manhã
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/Platane/snk.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories || true

      - name: Push changes to fork
        run: |
          git push origin main
